In [1]:
import torch

In [2]:
x=torch.empty(5 ,3)
print(x)

tensor([[4.9550e-25, 7.3848e-43, 4.9550e-25],
        [7.3848e-43, 4.9551e-25, 7.3848e-43],
        [4.9530e-25, 7.3848e-43, 4.9535e-25],
        [7.3848e-43, 4.9535e-25, 7.3848e-43],
        [4.9543e-25, 7.3848e-43, 4.9543e-25]])


In [3]:
x=torch.rand(5 ,3)
x

tensor([[0.0663, 0.7482, 0.6705],
        [0.5673, 0.6858, 0.9957],
        [0.1995, 0.9704, 0.6617],
        [0.8390, 0.1552, 0.8407],
        [0.0208, 0.2943, 0.1185]])

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
x=torch.tensor([5.5 ,3])
x

tensor([5.5000, 3.0000])

In [6]:
x=x.new_ones(5 ,3 ,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
x=torch.randn_like(x , dtype=torch.float)
x

tensor([[ 0.0742, -0.5926, -0.8362],
        [ 1.6020,  0.1156, -0.6026],
        [-1.7699, -0.3826,  1.2423],
        [ 0.0107,  0.0350,  0.6535],
        [-1.8180,  0.2996,  0.7584]])

In [8]:
x.size()

torch.Size([5, 3])

## テンソルの演算

In [9]:
y=torch.rand(5 ,3)
y

tensor([[0.2487, 0.8099, 0.6038],
        [0.5365, 0.4177, 0.2772],
        [0.6512, 0.6627, 0.1418],
        [0.1979, 0.3731, 0.7058],
        [0.4081, 0.7673, 0.0448]])

In [10]:
x+y

tensor([[ 0.3229,  0.2172, -0.2324],
        [ 2.1385,  0.5334, -0.3254],
        [-1.1188,  0.2801,  1.3841],
        [ 0.2086,  0.4081,  1.3593],
        [-1.4099,  1.0669,  0.8032]])

In [11]:
torch.add(x,y)

tensor([[ 0.3229,  0.2172, -0.2324],
        [ 2.1385,  0.5334, -0.3254],
        [-1.1188,  0.2801,  1.3841],
        [ 0.2086,  0.4081,  1.3593],
        [-1.4099,  1.0669,  0.8032]])

In [12]:
x[:,1]

tensor([-0.5926,  0.1156, -0.3826,  0.0350,  0.2996])

# NumPyとの連携

In [13]:
import numpy as np

In [19]:
# pytorchの配列宣言
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [20]:
b=a.numpy()

In [21]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [22]:
# 全項目に１を足す
a.add_(1) 

tensor([2., 2., 2., 2., 2.])

In [23]:
# メモリを共有しているため、一緒に変わる
b

array([2., 2., 2., 2., 2.], dtype=float32)

# NumPy からtorchへ

In [25]:
# nuumpyの配列を宣言する
c=np.ones(5)
# numpyの配列をpytorchの変数へ格納する
d=torch.from_numpy(c)

In [26]:
c

array([1., 1., 1., 1., 1.])

In [27]:
d

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [30]:
# 全項目に１を足す
np.add(c ,1, out=c)

array([3., 3., 3., 3., 3.])

In [31]:
# メモリを共有しているため、一緒に変わる
d

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)