# 元の計算式の定義

In [1]:
import torch

In [2]:
x=torch.ones(2 ,2 ,requires_grad=True)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2

In [5]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
y.grad_fn

In [7]:
z=y*y*3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [8]:
out=z.mean()

In [9]:
out

tensor(27., grad_fn=<MeanBackward0>)

# 反転

In [11]:
a=torch.randn(2,2)

In [13]:
a.requires_grad

False

In [14]:
a.requires_grad_(True)

tensor([[-0.2181,  0.7568],
        [ 0.1632,  1.4577]], requires_grad=True)

In [15]:
a.requires_grad

True

In [16]:
b = (a * a).sum()

In [17]:
b

tensor(2.7718, grad_fn=<SumBackward0>)

In [18]:
b.grad_fn

# backward() で微分値を求める

In [19]:
# 微分値を持たせる
out.backward()

In [20]:
# xで微分した結果を表示する
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])